#!/bin/bash

if [ -n "$SEG_DEBUG" ] ; then
    set -x
    env | sort
fi

cd $WEST_SIM_ROOT || exit 1

cp west.h5 west_prev.h5 &
### BACKING UP THE H5 FILE AFTER EVERY ITERATION

ITER=$(printf "%06d" $WEST_CURRENT_ITER)
PAR_ITER=$(printf "%06d" $((WEST_CURRENT_ITER-1)))
rm  -f  seg_logs/$ITER-*.log &
rm  -f  traj_segs/$PAR_ITER/*/seg.* &

### IN ORDER TO SAVE SPACE, REMOVING ALL CURRENT LOG FILES AND ALL FILES FROM THE PREVIOUS "PARENT" ITERATION, WHICH WERE NOT DELETED EARLIER BECAUSE SOME WERE NEEDED TO START THE CURRENT GROMACS RUNS ('seg.gro' BECOMING 'parent.gro', 'seg.edr' BECOMING 'parent.edr'). [THEY DID NOT GET DELETED AT THE END OF RUNNING A CURRENT SEGMENT EITHER BECAUSE THEY MAY BE THE PARENTS OF MORE THAN ONE CURRENT SEGMENT, THUS THEY CAN ONLY BE DELETED HERE WHEN THE WHOLE ITERATION IS OVER]
### OVERALL, THE ONLY FILES LEFT IN EVERY SEGMENT TRAJECTORY SUBDIRECTORY ARE 'pcoord.dat', SO ONE CAN MONITOR ITS PROGRESS WHILE WESTPA IS RUNNING W/O READING IN THE H5 FILE, AND 'seg_whole.pdb', SO ALL SEGMENT (WATER-STRIPPED) SUBSTRUCTURES ARE AVAILABLE FOR FURTHER ANALYSIS OR VISUALIZATION
 
